{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "sys.path.append(\"..\")\n",
    "\n",
    "from libs.InteractivePitchUI import *\n",
    "from libs.data_manipulation import *\n",
    "from libs.dim_reduction import *\n",
    "from libs.feature_generation import *\n",
    "from libs.clustering import *\n",
    "from libs.convex_hull import *\n",
    "from libs.alpha_shape import *\n",
    "from libs.weight_generator import *\n",
    "from libs.similar_movement import *\n",
    "from libs.Video_Player import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "matches = compile_team_tracking_data_with_labels(\"../data/H_EURO2024GERMANY\", \"Denmark\", \"../data/Labelled_ground_truths.csv\")\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = extract_one_match(matches,4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['match_id', 'Time [s]', 'Time [s]_team', 'half_team', 'minute_team',\n",
       "       'Period_team', 'home_6_x', 'home_6_y', 'home_18_x', 'home_18_y',\n",
       "       ...\n",
       "       'away_25_y', 'home_26_x', 'home_26_y', 'away_3_x', 'away_3_y',\n",
       "       'away_15_x', 'away_15_y', 'Label', 'Time[s]', 'Competition'],\n",
       "      dtype='object', length=101)"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()\n",
    "df.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "df = df[df[\"match_name\"].isin([\"Denmark_England\",\"Slovenia_Denmark\"])]\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "func_control = lambda x:1\n",
    "func_inverse = lambda x: 20/x\n",
    "func_linear = lambda x: 200-x\n",
    "func_exp = lambda x: np.exp(-x/20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array(['Missing', 'breakthrough-wb', 'run-into-space',\n",
       "       'breakthrough-even', 'breakthrough-space'], dtype=object)"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.Label.unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[1675, 8725, 12300, 39000, 48500, 85241, 93791, 129716, 143547, 154347, 181797, 189572, 199447, 208722, 214138]\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-wb_Slovenia_Denmark_0:01:07' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'run-into-space_Slovenia_Denmark_0:05:49' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-wb_Slovenia_Denmark_0:08:12' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-even_Slovenia_Denmark_0:26:00' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-even_Slovenia_Denmark_0:32:20' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-even_Slovenia_Denmark_0:55:49' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-even_Slovenia_Denmark_1:01:31' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-space_Slovenia_Denmark_1:25:28' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'run-into-space_Denmark_England_0:00:10' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-wb_Denmark_England_0:07:22' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-space_Denmark_England_0:25:40' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-space_Denmark_England_0:30:51' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-space_Denmark_England_0:37:26' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'run-into-space_Denmark_England_0:43:37' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "21284\n",
      "21284\n",
      "21284\n",
      "21284\n",
      "Folder 'breakthrough-even_Denmark_England_0:46:06' does not exist.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
      "/tmp/ipykernel_4115/259074268.py:84: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n"
     ]
    }
   ],
   "source": [
    "import datetime\n",
    "\n",
    "\n",
    "def process_situations(df):\n",
    "    # Dictionary to store recommendations\n",
    "    recommendations_dict = {}\n",
    "\n",
    "    # Step 2: Extract relevant rows (all rows with a label not equal to \"Missing\")\n",
    "    labeled_rows = df[df['Label'] != \"Missing\"]\n",
    "    relevant_indices = labeled_rows.index.tolist()\n",
    "    print(relevant_indices)\n",
    "    # Step 2: Process each relevant index\n",
    "    # Step 2: Process each relevant index\n",
    "    for relevant_index in relevant_indices:\n",
    "        # Step 3: Apply Wasserstein distance for various functions upfront\n",
    "        finished_indices_control = most_similar_with_wasserstein_closed_interval(relevant_index, df, func_control)\n",
    "        finished_indices_linear = most_similar_with_wasserstein_closed_interval(relevant_index, df, func_linear)\n",
    "        finished_indices_inverse = most_similar_with_wasserstein_closed_interval(relevant_index, df, func_inverse)\n",
    "        finished_indices_exp = most_similar_with_wasserstein_closed_interval(relevant_index, df, func_exp)\n",
    "\n",
    "        # Convert to numpy arrays\n",
    "        finished_indices_control = np.array(finished_indices_control)\n",
    "        finished_indices_exp = np.array(finished_indices_exp)\n",
    "        finished_indices_linear = np.array(finished_indices_linear)\n",
    "        finished_indices_inverse = np.array(finished_indices_inverse)\n",
    "\n",
    "        # Step 4: Filter indices based on the time window (±480 seconds)\n",
    "        time_window_filter = lambda indices: indices[\n",
    "            (indices > relevant_index + 480) | \n",
    "            (indices < relevant_index - 480)\n",
    "        ]\n",
    "\n",
    "        finished_indices_control = time_window_filter(finished_indices_control)[:100]\n",
    "        finished_indices_exp = time_window_filter(finished_indices_exp)[:100]\n",
    "        finished_indices_linear = time_window_filter(finished_indices_linear)[:100]\n",
    "        finished_indices_inverse = time_window_filter(finished_indices_inverse)[:100]\n",
    "\n",
    "        # Combine recommendations into a dictionary for separate processing\n",
    "        wasserstein_recommendations = {\n",
    "            \"Control\": finished_indices_control,\n",
    "            \"Exp\": finished_indices_exp,\n",
    "            \"Linear\": finished_indices_linear,\n",
    "            \"Inverse\": finished_indices_inverse\n",
    "        }\n",
    "        # Create the folder based on the label\n",
    "        # Step 6: Prepare the result DataFrame for this function set\n",
    "        label = df.loc[relevant_index, 'Label']  # Get the label for the situation\n",
    "        match_name = df.loc[relevant_index, 'match_name']\n",
    "        time_of_situation = str(datetime.timedelta(seconds=df.loc[relevant_index, 'Time [s]']))\n",
    "\n",
    "        folder_name = f\"{label}_{match_name}_{time_of_situation}\"\n",
    "        generate_folder(folder_name)\n",
    "\n",
    "        # Save the time and match_name to a text file\n",
    "        with open(f\"{folder_name}/situation_info.txt\", \"w\") as f:\n",
    "                f.write(f\"Match Name: {match_name}\\n\")\n",
    "                f.write(f\"Time of Situation: {time_of_situation}\\n\")\n",
    "\n",
    "        # Step 5: Process each set of indices separately\n",
    "        for func_name, indices_set in wasserstein_recommendations.items():\n",
    "            if len(indices_set) == 0:\n",
    "                continue  # Skip if no indices in this set\n",
    "\n",
    "            # Step 5.1: Compute similar movements for the current set\n",
    "            similar_movement = find_similar_movement(df, relevant_index, indices_set,length_of_sequence=120)\n",
    "            similar_movement_ranked = sorted(similar_movement, key=lambda x: x[0])\n",
    "\n",
    "            # Step 5.2: Select indices, ensuring no two are within 100 places of each other\n",
    "            selected_indices = []\n",
    "            for _, index in similar_movement_ranked:\n",
    "                if all(abs(index - selected) > 500 for selected in selected_indices):\n",
    "                    selected_indices.append(index)\n",
    "                if len(selected_indices) == 10:  # Stop once we have 10 indices\n",
    "                    break\n",
    "\n",
    "            new_df = df.loc[selected_indices[:10]]\n",
    "\n",
    "            \n",
    "            \n",
    "\n",
    "\n",
    "            # Generate the result DataFrame\n",
    "            result_df = new_df[[\"match_name\", \"Time [s]\", \"half_team\"]]\n",
    "            result_df[\"Time Min\"] = result_df[\"Time [s]\"].apply(lambda x: str(datetime.timedelta(seconds=x)))\n",
    "\n",
    "            # Save the ground truth CSV for this function set\n",
    "            result_df.to_csv(f\"{folder_name}/{folder_name}_{func_name}_ground_truth.csv\")\n",
    "\n",
    "            # Shuffle and save the ordering truth CSV for this function set\n",
    "            result_df.sample(frac=1).to_csv(f\"{folder_name}/{folder_name}_{func_name}_for_ordering_truth.csv\")\n",
    "\n",
    "            # Store the recommendations in the dictionary\n",
    "            recommendations_dict[relevant_index] = recommendations_dict.get(relevant_index, {})\n",
    "            recommendations_dict[relevant_index][func_name] = selected_indices[:10]\n",
    "\n",
    "    # Return the dictionary with recommendations\n",
    "    return recommendations_dict\n",
    "\n",
    "    \n",
    "\n",
    "reccomendations_dict = process_situations(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{1675: {'Control': [62112,\n",
       "   128040,\n",
       "   2880,\n",
       "   165408,\n",
       "   149796,\n",
       "   52332,\n",
       "   39084,\n",
       "   189300,\n",
       "   6228,\n",
       "   259068],\n",
       "  'Exp': [125112,\n",
       "   273372,\n",
       "   62088,\n",
       "   172572,\n",
       "   258972,\n",
       "   1188,\n",
       "   204324,\n",
       "   128040,\n",
       "   243720,\n",
       "   2880],\n",
       "  'Linear': [62112,\n",
       "   128040,\n",
       "   2880,\n",
       "   165408,\n",
       "   149796,\n",
       "   52332,\n",
       "   39084,\n",
       "   189300,\n",
       "   6228,\n",
       "   259068],\n",
       "  'Inverse': [125124,\n",
       "   273408,\n",
       "   62088,\n",
       "   258984,\n",
       "   1188,\n",
       "   128040,\n",
       "   243720,\n",
       "   172584,\n",
       "   2880,\n",
       "   68364]},\n",
       " 8725: {'Control': [143808,\n",
       "   139620,\n",
       "   154392,\n",
       "   189552,\n",
       "   187872,\n",
       "   73404,\n",
       "   201312,\n",
       "   39096,\n",
       "   173892,\n",
       "   63084],\n",
       "  'Exp': [97524,\n",
       "   17628,\n",
       "   278160,\n",
       "   221904,\n",
       "   15684,\n",
       "   193632,\n",
       "   44820,\n",
       "   259260,\n",
       "   143808,\n",
       "   106380],\n",
       "  'Linear': [143808,\n",
       "   139620,\n",
       "   154392,\n",
       "   189552,\n",
       "   187872,\n",
       "   73404,\n",
       "   201312,\n",
       "   39096,\n",
       "   173892,\n",
       "   63084],\n",
       "  'Inverse': [97524,\n",
       "   44820,\n",
       "   259260,\n",
       "   143808,\n",
       "   221916,\n",
       "   73392,\n",
       "   139620,\n",
       "   187872,\n",
       "   154380,\n",
       "   39816]},\n",
       " 12300: {'Control': [143844,\n",
       "   154416,\n",
       "   129816,\n",
       "   45792,\n",
       "   2568,\n",
       "   150168,\n",
       "   8784,\n",
       "   68544,\n",
       "   19476,\n",
       "   14820],\n",
       "  'Exp': [8760,\n",
       "   221952,\n",
       "   44844,\n",
       "   143856,\n",
       "   186996,\n",
       "   181764,\n",
       "   39828,\n",
       "   151692,\n",
       "   175272,\n",
       "   129336],\n",
       "  'Linear': [143844,\n",
       "   154416,\n",
       "   129816,\n",
       "   45792,\n",
       "   2568,\n",
       "   150168,\n",
       "   8784,\n",
       "   68544,\n",
       "   19476,\n",
       "   14820],\n",
       "  'Inverse': [8760,\n",
       "   143856,\n",
       "   186996,\n",
       "   129816,\n",
       "   1968,\n",
       "   150168,\n",
       "   259320,\n",
       "   14820,\n",
       "   192624,\n",
       "   174972]},\n",
       " 39000: {'Control': [209436,\n",
       "   44736,\n",
       "   214164,\n",
       "   172524,\n",
       "   62064,\n",
       "   212856,\n",
       "   151200,\n",
       "   221844,\n",
       "   12048,\n",
       "   1188],\n",
       "  'Exp': [257880,\n",
       "   209436,\n",
       "   98592,\n",
       "   214164,\n",
       "   143580,\n",
       "   62064,\n",
       "   1224,\n",
       "   219408,\n",
       "   260112,\n",
       "   212856],\n",
       "  'Linear': [209436,\n",
       "   44736,\n",
       "   214164,\n",
       "   172524,\n",
       "   62064,\n",
       "   212856,\n",
       "   151200,\n",
       "   221844,\n",
       "   12048,\n",
       "   1188],\n",
       "  'Inverse': [209436,\n",
       "   98592,\n",
       "   214164,\n",
       "   172524,\n",
       "   62064,\n",
       "   1224,\n",
       "   219408,\n",
       "   260112,\n",
       "   212856,\n",
       "   151164]},\n",
       " 48500: {'Control': [38700, 57228, 300, 221400, 160116, 120816, 204036, 37536],\n",
       "  'Exp': [38700,\n",
       "   61704,\n",
       "   57108,\n",
       "   120792,\n",
       "   241572,\n",
       "   243228,\n",
       "   160116,\n",
       "   218196,\n",
       "   212064,\n",
       "   195612],\n",
       "  'Linear': [38700, 57228, 300, 221400, 160116, 120816, 204036, 37536],\n",
       "  'Inverse': [38700,\n",
       "   57228,\n",
       "   120792,\n",
       "   223956,\n",
       "   160140,\n",
       "   243228,\n",
       "   218196,\n",
       "   195888,\n",
       "   137004]},\n",
       " 85241: {'Control': [12120,\n",
       "   139620,\n",
       "   214260,\n",
       "   224652,\n",
       "   7080,\n",
       "   137736,\n",
       "   154284,\n",
       "   63828,\n",
       "   67332,\n",
       "   231300],\n",
       "  'Exp': [203112,\n",
       "   27072,\n",
       "   249636,\n",
       "   45300,\n",
       "   166176,\n",
       "   12096,\n",
       "   146724,\n",
       "   114792,\n",
       "   19344,\n",
       "   34956],\n",
       "  'Linear': [12120,\n",
       "   139620,\n",
       "   214260,\n",
       "   224652,\n",
       "   7080,\n",
       "   137736,\n",
       "   154284,\n",
       "   63828,\n",
       "   67332,\n",
       "   231300],\n",
       "  'Inverse': [151632,\n",
       "   12096,\n",
       "   139620,\n",
       "   19344,\n",
       "   224652,\n",
       "   186864,\n",
       "   261648,\n",
       "   129120,\n",
       "   7080,\n",
       "   154284]},\n",
       " 93791: {'Control': [181068,\n",
       "   73872,\n",
       "   5124,\n",
       "   198768,\n",
       "   207900,\n",
       "   68880,\n",
       "   52944,\n",
       "   252948,\n",
       "   253512,\n",
       "   149256],\n",
       "  'Exp': [252672,\n",
       "   179364,\n",
       "   173928,\n",
       "   185268,\n",
       "   243504,\n",
       "   8940,\n",
       "   189624,\n",
       "   73884,\n",
       "   58236,\n",
       "   207888],\n",
       "  'Linear': [181068,\n",
       "   73872,\n",
       "   5124,\n",
       "   198768,\n",
       "   207900,\n",
       "   68880,\n",
       "   52944,\n",
       "   252948,\n",
       "   253512,\n",
       "   149256],\n",
       "  'Inverse': [181380,\n",
       "   58248,\n",
       "   74268,\n",
       "   185268,\n",
       "   189636,\n",
       "   52824,\n",
       "   5124,\n",
       "   207876,\n",
       "   93300,\n",
       "   149184]},\n",
       " 129716: {'Control': [3120,\n",
       "   59172,\n",
       "   172896,\n",
       "   179112,\n",
       "   259212,\n",
       "   19764,\n",
       "   149964,\n",
       "   6564],\n",
       "  'Exp': [1932,\n",
       "   12228,\n",
       "   231888,\n",
       "   128532,\n",
       "   3120,\n",
       "   150084,\n",
       "   129216,\n",
       "   6264,\n",
       "   59172,\n",
       "   259104],\n",
       "  'Linear': [3120, 59172, 172896, 179112, 259212, 19764, 149964, 6564],\n",
       "  'Inverse': [1932,\n",
       "   12228,\n",
       "   3120,\n",
       "   150084,\n",
       "   129228,\n",
       "   59172,\n",
       "   259116,\n",
       "   231912,\n",
       "   172896,\n",
       "   214308]},\n",
       " 143547: {'Control': [234468,\n",
       "   282456,\n",
       "   106164,\n",
       "   252492,\n",
       "   146676,\n",
       "   91176,\n",
       "   241632,\n",
       "   169824,\n",
       "   31800,\n",
       "   31248],\n",
       "  'Exp': [282432,\n",
       "   172524,\n",
       "   39012,\n",
       "   137148,\n",
       "   261552,\n",
       "   204288,\n",
       "   278052,\n",
       "   121056,\n",
       "   22116,\n",
       "   214176],\n",
       "  'Linear': [234468,\n",
       "   282456,\n",
       "   106164,\n",
       "   252492,\n",
       "   146676,\n",
       "   91176,\n",
       "   241632,\n",
       "   169824,\n",
       "   31800,\n",
       "   31248],\n",
       "  'Inverse': [282420,\n",
       "   263472,\n",
       "   278028,\n",
       "   137148,\n",
       "   261552,\n",
       "   204288,\n",
       "   121056,\n",
       "   22116,\n",
       "   230304,\n",
       "   283008]},\n",
       " 154347: {'Control': [139692,\n",
       "   173868,\n",
       "   137736,\n",
       "   187848,\n",
       "   52500,\n",
       "   85236,\n",
       "   8676,\n",
       "   143796,\n",
       "   63072,\n",
       "   2556],\n",
       "  'Exp': [139692,\n",
       "   173868,\n",
       "   137736,\n",
       "   246396,\n",
       "   187848,\n",
       "   52500,\n",
       "   97896,\n",
       "   8676,\n",
       "   203172,\n",
       "   143796],\n",
       "  'Linear': [139692,\n",
       "   173868,\n",
       "   137736,\n",
       "   187848,\n",
       "   52500,\n",
       "   85236,\n",
       "   8676,\n",
       "   143796,\n",
       "   63072,\n",
       "   2556],\n",
       "  'Inverse': [139692,\n",
       "   173868,\n",
       "   137736,\n",
       "   246396,\n",
       "   187848,\n",
       "   52500,\n",
       "   97896,\n",
       "   8664,\n",
       "   143796,\n",
       "   12348]},\n",
       " 181797: {'Control': [199524,\n",
       "   176316,\n",
       "   207996,\n",
       "   185292,\n",
       "   58248,\n",
       "   179400,\n",
       "   189672,\n",
       "   174660,\n",
       "   253596],\n",
       "  'Exp': [106392,\n",
       "   44832,\n",
       "   8748,\n",
       "   197772,\n",
       "   39828,\n",
       "   243516,\n",
       "   208752,\n",
       "   259284,\n",
       "   46008,\n",
       "   27240],\n",
       "  'Linear': [199524,\n",
       "   176316,\n",
       "   207996,\n",
       "   185292,\n",
       "   58248,\n",
       "   179400,\n",
       "   189672,\n",
       "   174660,\n",
       "   253596],\n",
       "  'Inverse': [208764,\n",
       "   46008,\n",
       "   253692,\n",
       "   173928,\n",
       "   207996,\n",
       "   2628,\n",
       "   68568,\n",
       "   185292,\n",
       "   8772,\n",
       "   193584]},\n",
       " 189572: {'Control': [253392,\n",
       "   58164,\n",
       "   181032,\n",
       "   171744,\n",
       "   63084,\n",
       "   198768,\n",
       "   185052,\n",
       "   199368,\n",
       "   216024,\n",
       "   149712],\n",
       "  'Exp': [253392,\n",
       "   58164,\n",
       "   102036,\n",
       "   243480,\n",
       "   181032,\n",
       "   201324,\n",
       "   2568,\n",
       "   176124,\n",
       "   174348,\n",
       "   179208],\n",
       "  'Linear': [253392,\n",
       "   58164,\n",
       "   181032,\n",
       "   171744,\n",
       "   63084,\n",
       "   198768,\n",
       "   185052,\n",
       "   199368,\n",
       "   216024,\n",
       "   149712],\n",
       "  'Inverse': [253392,\n",
       "   58164,\n",
       "   181032,\n",
       "   201324,\n",
       "   2568,\n",
       "   171744,\n",
       "   63084,\n",
       "   176124,\n",
       "   173904,\n",
       "   198768]},\n",
       " 199447: {'Control': [2664,\n",
       "   253608,\n",
       "   189684,\n",
       "   149760,\n",
       "   208848,\n",
       "   179280,\n",
       "   207936,\n",
       "   58272,\n",
       "   185148,\n",
       "   181092],\n",
       "  'Exp': [87852,\n",
       "   270936,\n",
       "   174612,\n",
       "   82416,\n",
       "   163776,\n",
       "   226224,\n",
       "   283836,\n",
       "   9084,\n",
       "   2664,\n",
       "   253608],\n",
       "  'Linear': [2664,\n",
       "   253608,\n",
       "   189684,\n",
       "   149760,\n",
       "   208848,\n",
       "   179280,\n",
       "   207936,\n",
       "   58272,\n",
       "   185148,\n",
       "   181092],\n",
       "  'Inverse': [270936,\n",
       "   174612,\n",
       "   163788,\n",
       "   2664,\n",
       "   253608,\n",
       "   189696,\n",
       "   208056,\n",
       "   176232,\n",
       "   185340,\n",
       "   46044]},\n",
       " 208722: {'Control': [5052,\n",
       "   14004,\n",
       "   198720,\n",
       "   181020,\n",
       "   199416,\n",
       "   149568,\n",
       "   185124,\n",
       "   189648,\n",
       "   253428,\n",
       "   207900],\n",
       "  'Exp': [44796,\n",
       "   234456,\n",
       "   28488,\n",
       "   97536,\n",
       "   106392,\n",
       "   42960,\n",
       "   181776,\n",
       "   157764,\n",
       "   197760,\n",
       "   238644],\n",
       "  'Linear': [5052,\n",
       "   14004,\n",
       "   198720,\n",
       "   181020,\n",
       "   199416,\n",
       "   149568,\n",
       "   185124,\n",
       "   189648,\n",
       "   253428,\n",
       "   207900],\n",
       "  'Inverse': [28488,\n",
       "   106380,\n",
       "   181776,\n",
       "   44832,\n",
       "   39888,\n",
       "   50028,\n",
       "   46020,\n",
       "   53736,\n",
       "   27240,\n",
       "   197796]},\n",
       " 214138: {'Control': [38976,\n",
       "   62052,\n",
       "   151176,\n",
       "   224484,\n",
       "   237888,\n",
       "   264984,\n",
       "   87180,\n",
       "   166980,\n",
       "   212880,\n",
       "   12048],\n",
       "  'Exp': [63720,\n",
       "   212844,\n",
       "   98520,\n",
       "   67284,\n",
       "   88476,\n",
       "   151176,\n",
       "   1236,\n",
       "   79968,\n",
       "   129084,\n",
       "   269040],\n",
       "  'Linear': [38976,\n",
       "   62052,\n",
       "   151176,\n",
       "   224484,\n",
       "   237888,\n",
       "   264984,\n",
       "   87180,\n",
       "   166980,\n",
       "   212880,\n",
       "   12048],\n",
       "  'Inverse': [63720,\n",
       "   212844,\n",
       "   38976,\n",
       "   98520,\n",
       "   88476,\n",
       "   151176,\n",
       "   1236,\n",
       "   79968,\n",
       "   137220,\n",
       "   224484]}}"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "reccomendations_dict"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "run-into-space_Denmark_England_0:43:37\n",
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f2550003250] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f2550003250] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2550003250] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2550003250] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2550003250] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f2550003250] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24dd4c96b0] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798074182976update_time_label\"\n",
      "    while executing\n",
      "\"139798074182976update_time_label\"\n",
      "    (\"after\" script)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f24e4001720] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f24e4001720] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f24e4001720] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f24e4001720] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f24e4001720] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f24e4001720] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24d952dd60] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798751174656update_time_label\"\n",
      "    while executing\n",
      "\"139798751174656update_time_label\"\n",
      "    (\"after\" script)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f253c008750] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f253c008750] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f253c008750] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f253c008750] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f253c008750] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f253c008750] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24d93db440] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798074426560update_time_label\"\n",
      "    while executing\n",
      "\"139798074426560update_time_label\"\n",
      "    (\"after\" script)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[]\n",
      "run-into-space_Denmark_England_0:43:37\n",
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f25100c36c0] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f25100c36c0] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f25100c36c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f25100c36c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f25100c36c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f25100c36c0] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24c94ca1d0] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798073244416update_time_label\"\n",
      "    while executing\n",
      "\"139798073244416update_time_label\"\n",
      "    (\"after\" script)\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/martinaguayo/anaconda3/envs/DBU/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/media/martinaguayo/thesis_drive/Thesis/Thesis_V1/evaluation/../libs/Video_Player.py\", line 113, in next_time\n",
      "    if self.distance_index_list.any():\n",
      "AttributeError: 'list' object has no attribute 'any'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f254c9e4ec0] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f254c9e4ec0] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f254c9e4ec0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f254c9e4ec0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f254c9e4ec0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f254c9e4ec0] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24bd52e890] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798070777024update_time_label\"\n",
      "    while executing\n",
      "\"139798070777024update_time_label\"\n",
      "    (\"after\" script)\n",
      "[00007f24bd52e890] main decoder error: Timestamp conversion failed (delay 1000000, buffering 0, bound 9000000)\n",
      "[00007f24bd52e890] main decoder error: Could not convert timestamp 1917524605 for FFmpeg\n",
      "[00007f24bd52e890] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24bd52e890] main decoder error: Could not convert timestamp 1932426529 for FFmpeg\n",
      "[00007f24bd52e890] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24bd52e890] main decoder error: Could not convert timestamp 1928217600 for FFmpeg\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f25503cf4c0] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f25503cf4c0] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f25503cf4c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f25503cf4c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f25503cf4c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f25503cf4c0] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24b94c98d0] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798070777600update_time_label\"\n",
      "    while executing\n",
      "\"139798070777600update_time_label\"\n",
      "    (\"after\" script)\n",
      "[00007f24b94c98d0] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24b94c98d0] main decoder error: Could not convert timestamp 3605204408 for FFmpeg\n",
      "[00007f24b94c98d0] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24b94c98d0] main decoder error: Could not convert timestamp 4355266004 for FFmpeg\n",
      "[00007f24b94c98d0] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24b94c98d0] main decoder error: Could not convert timestamp 2003006001 for FFmpeg\n",
      "[00007f24b94c98d0] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24b94c98d0] main decoder error: Could not convert timestamp 2351148198 for FFmpeg\n",
      "[00007f24b94c98d0] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24b94c98d0] main decoder error: Could not convert timestamp 3644224574 for FFmpeg\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[]\n",
      "run-into-space_Denmark_England_0:43:37\n",
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f24e46038c0] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f24e46038c0] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f24e46038c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f24e46038c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f24e46038c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f24e46038c0] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24ad4ca2c0] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798074441152update_time_label\"\n",
      "    while executing\n",
      "\"139798074441152update_time_label\"\n",
      "    (\"after\" script)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f253c008920] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f253c008920] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f253c008920] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f253c008920] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f253c008920] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f253c008920] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24ace43c70] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798068612352update_time_label\"\n",
      "    while executing\n",
      "\"139798068612352update_time_label\"\n",
      "    (\"after\" script)\n",
      "[00007f24ace43c70] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24ace43c70] main decoder error: Could not convert timestamp 5118693735 for FFmpeg\n",
      "[00007f24ace43c70] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24ace43c70] main decoder error: Could not convert timestamp 2343889129 for FFmpeg\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f25100cf040] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f25100cf040] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f25100cf040] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f25100cf040] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f25100cf040] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f25100cf040] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24994c9530] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798070749760update_time_label\"\n",
      "    while executing\n",
      "\"139798070749760update_time_label\"\n",
      "    (\"after\" script)\n",
      "[00007f24994c9530] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24994c9530] main decoder error: Could not convert timestamp 2688929828 for FFmpeg\n",
      "[00007f24994c9530] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24994c9530] main decoder error: Could not convert timestamp 1907966618 for FFmpeg\n",
      "[00007f24994c9530] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24994c9530] main decoder error: Could not convert timestamp 4753137771 for FFmpeg\n",
      "[00007f24994c9530] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24994c9530] main decoder error: Could not convert timestamp 2707120815 for FFmpeg\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[]\n",
      "run-into-space_Denmark_England_0:43:37\n",
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f254c0026c0] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f254c0026c0] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f254c0026c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f254c0026c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f254c0026c0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f254c972c20] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24954c9b50] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798070752256update_time_label\"\n",
      "    while executing\n",
      "\"139798070752256update_time_label\"\n",
      "    (\"after\" script)\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/martinaguayo/anaconda3/envs/DBU/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/media/martinaguayo/thesis_drive/Thesis/Thesis_V1/evaluation/../libs/Video_Player.py\", line 113, in next_time\n",
      "    if self.distance_index_list.any():\n",
      "AttributeError: 'list' object has no attribute 'any'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f2550005ba0] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f2550005ba0] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2550005ba0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2550005ba0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2550005ba0] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f2550003860] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f248952e080] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798751115776update_time_label\"\n",
      "    while executing\n",
      "\"139798751115776update_time_label\"\n",
      "    (\"after\" script)\n",
      "[00007f248952e080] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f248952e080] main decoder error: Could not convert timestamp 2145235119 for FFmpeg\n",
      "[00007f248952e080] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f248952e080] main decoder error: Could not convert timestamp 2145251249 for FFmpeg\n",
      "[00007f248952e080] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f248952e080] main decoder error: Could not convert timestamp 2152401356 for FFmpeg\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f24e4177b80] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f24e4177b80] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f24e4177b80] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f24e4177b80] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f24e4177b80] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f24e4177b80] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24814cae50] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798070773568update_time_label\"\n",
      "    while executing\n",
      "\"139798070773568update_time_label\"\n",
      "    (\"after\" script)\n",
      "[00007f24814cae50] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24814cae50] main decoder error: Could not convert timestamp 3822961714 for FFmpeg\n",
      "[00007f24814cae50] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24814cae50] main decoder error: Could not convert timestamp 4572885390 for FFmpeg\n",
      "[00007f24814cae50] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24814cae50] main decoder error: Could not convert timestamp 2228229474 for FFmpeg\n",
      "[00007f24814cae50] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24814cae50] main decoder error: Could not convert timestamp 2564380820 for FFmpeg\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[]\n",
      "breakthrough-even_Slovenia_Denmark_0:26:00\n",
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f253d191410] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f253d191410] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f253d191410] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f253d191410] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f253d191410] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f253d191410] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f247952e2c0] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798070786432update_time_label\"\n",
      "    while executing\n",
      "\"139798070786432update_time_label\"\n",
      "    (\"after\" script)\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/martinaguayo/anaconda3/envs/DBU/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/media/martinaguayo/thesis_drive/Thesis/Thesis_V1/evaluation/../libs/Video_Player.py\", line 113, in next_time\n",
      "    if self.distance_index_list.any():\n",
      "AttributeError: 'list' object has no attribute 'any'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/martinaguayo/anaconda3/envs/DBU/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/media/martinaguayo/thesis_drive/Thesis/Thesis_V1/evaluation/../libs/Video_Player.py\", line 113, in next_time\n",
      "    if self.distance_index_list.any():\n",
      "AttributeError: 'list' object has no attribute 'any'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f2438001720] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f2438001720] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2438001720] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2438001720] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2438001720] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f2438001720] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f245952dbb0] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798070783808update_time_label\"\n",
      "    while executing\n",
      "\"139798070783808update_time_label\"\n",
      "    (\"after\" script)\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/martinaguayo/anaconda3/envs/DBU/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/media/martinaguayo/thesis_drive/Thesis/Thesis_V1/evaluation/../libs/Video_Player.py\", line 113, in next_time\n",
      "    if self.distance_index_list.any():\n",
      "AttributeError: 'list' object has no attribute 'any'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/martinaguayo/anaconda3/envs/DBU/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/media/martinaguayo/thesis_drive/Thesis/Thesis_V1/evaluation/../libs/Video_Player.py\", line 113, in next_time\n",
      "    if self.distance_index_list.any():\n",
      "AttributeError: 'list' object has no attribute 'any'\n",
      "Exception in Tkinter callback\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/martinaguayo/anaconda3/envs/DBU/lib/python3.10/tkinter/__init__.py\", line 1921, in __call__\n",
      "    return self.func(*args)\n",
      "  File \"/media/martinaguayo/thesis_drive/Thesis/Thesis_V1/evaluation/../libs/Video_Player.py\", line 113, in next_time\n",
      "    if self.distance_index_list.any():\n",
      "AttributeError: 'list' object has no attribute 'any'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Creating Pause Button\n",
      "Creating Play Button\n",
      "Creating Next Button\n",
      "Creating Previous Button\n",
      "Creating Close Button\n",
      "Creating Time Label\n",
      "Creating Negative Rating Button\n",
      "Creating Positiv Rating Button\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[00007f2428001720] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "libva info: VA-API version 1.18.0\n",
      "libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)\n",
      "[00007f2428001720] glconv_vaapi_x11 gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2428001720] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/simpledrm_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2428001720] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "libva info: VA-API version 1.18.0\n",
      "libva info: Trying to open /home/martinaguayo/anaconda3/envs/DBU/lib/dri/nvidia_drv_video.so\n",
      "libva info: va_openDriver() returns -1\n",
      "[00007f2428001720] glconv_vaapi_drm gl error: vaInitialize: unknown libva error\n",
      "[00007f2428001720] gl gl: Initialized libplacebo v4.192.1 (API v192)\n",
      "[00007f24593daa60] avcodec decoder: Using NVIDIA VDPAU Driver Shared Library  550.54.14  Thu Feb 22 01:24:07 UTC 2024 for hardware decoding\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Initial Time: 0 seconds\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "invalid command name \"139798070784704update_time_label\"\n",
      "    while executing\n",
      "\"139798070784704update_time_label\"\n",
      "    (\"after\" script)\n",
      "[00007f24593daa60] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24593daa60] main decoder error: Could not convert timestamp 3016683192 for FFmpeg\n",
      "[00007f24593daa60] main decoder error: Timestamp conversion failed (delay 1000000, buffering 100000, bound 9000000)\n",
      "[00007f24593daa60] main decoder error: Could not convert timestamp 4515357001 for FFmpeg\n",
      "[00007f24995717e0] xcb_window window error: X server failure\n",
      "X Error of failed request:  GLXBadWindow\n",
      "  Major opcode of failed request:  152 (GLX)\n",
      "  Minor opcode of failed request:  26 (X_GLXMakeContextCurrent)\n",
      "  Serial number of failed request:  12102\n",
      "  Current serial number in output stream:  12102\n",
      "[00007f247952e2c0] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f24795dea00] get_buffer() failed\n",
      "[h264 @ 0x7f24795dea00] thread_get_buffer() failed\n",
      "[h264 @ 0x7f24795dea00] decode_slice_header error\n",
      "[h264 @ 0x7f24795dea00] no frame!\n",
      "[00007f24593daa60] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f2459434a40] get_buffer() failed\n",
      "[h264 @ 0x7f2459434a40] thread_get_buffer() failed\n",
      "[h264 @ 0x7f2459434a40] decode_slice_header error\n",
      "[h264 @ 0x7f2459434a40] no frame!\n",
      "[00007f247952e2c0] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f24795fba00] get_buffer() failed\n",
      "[h264 @ 0x7f24795fba00] thread_get_buffer() failed\n",
      "[h264 @ 0x7f24795fba00] decode_slice_header error\n",
      "[h264 @ 0x7f24795fba00] no frame!\n",
      "[00007f24593daa60] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f2459451680] get_buffer() failed\n",
      "[h264 @ 0x7f2459451680] thread_get_buffer() failed\n",
      "[h264 @ 0x7f2459451680] decode_slice_header error\n",
      "[h264 @ 0x7f2459451680] no frame!\n",
      "[00007f247952e2c0] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f247953f580] get_buffer() failed\n",
      "[h264 @ 0x7f247953f580] thread_get_buffer() failed\n",
      "[h264 @ 0x7f247953f580] decode_slice_header error\n",
      "[h264 @ 0x7f247953f580] no frame!\n",
      "[00007f24593daa60] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f245946e7c0] get_buffer() failed\n",
      "[h264 @ 0x7f245946e7c0] thread_get_buffer() failed\n",
      "[h264 @ 0x7f245946e7c0] decode_slice_header error\n",
      "[h264 @ 0x7f245946e7c0] no frame!\n",
      "[00007f247952e2c0] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f2479587f00] get_buffer() failed\n",
      "[h264 @ 0x7f2479587f00] thread_get_buffer() failed\n",
      "[h264 @ 0x7f2479587f00] decode_slice_header error\n",
      "[h264 @ 0x7f2479587f00] no frame!\n",
      "[00007f24593daa60] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f245948b8c0] get_buffer() failed\n",
      "[h264 @ 0x7f245948b8c0] thread_get_buffer() failed\n",
      "[h264 @ 0x7f245948b8c0] decode_slice_header error\n",
      "[h264 @ 0x7f245948b8c0] no frame!\n",
      "[00007f24200ca8d0] xcb_window window error: X server failure\n",
      "[00007f247952e2c0] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f24795a4a00] get_buffer() failed\n",
      "[h264 @ 0x7f24795a4a00] thread_get_buffer() failed\n",
      "[h264 @ 0x7f24795a4a00] decode_slice_header error\n",
      "[h264 @ 0x7f24795a4a00] no frame!\n",
      "[00007f24593daa60] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f24594a89c0] get_buffer() failed\n",
      "[h264 @ 0x7f24594a89c0] thread_get_buffer() failed\n",
      "[h264 @ 0x7f24594a89c0] decode_slice_header error\n",
      "[h264 @ 0x7f24594a89c0] no frame!\n",
      "[00007f247952e2c0] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f24795c1a00] get_buffer() failed\n",
      "[h264 @ 0x7f24795c1a00] thread_get_buffer() failed\n",
      "[h264 @ 0x7f24795c1a00] decode_slice_header error\n",
      "[h264 @ 0x7f24795c1a00] no frame!\n",
      "[00007f247952e2c0] avcodec decoder error: more than 5 seconds of late video -> dropping frame (computer too slow ?)\n",
      "[00007f247952e2c0] avcodec decoder error: more than 5 seconds of late video -> dropping frame (computer too slow ?)\n",
      "[00007f247952e2c0] avcodec decoder error: more than 5 seconds of late video -> dropping frame (computer too slow ?)\n",
      "[00007f24593daa60] avcodec decoder error: hardware acceleration picture allocation failed\n",
      "[h264 @ 0x7f24593ebe80] get_buffer() failed\n",
      "[h264 @ 0x7f24593ebe80] thread_get_buffer() failed\n",
      "[h264 @ 0x7f24593ebe80] decode_slice_header error\n",
      "[h264 @ 0x7f24593ebe80] no frame!\n"
     ]
    },
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mThe Kernel crashed while executing code in the current cell or a previous cell. \n",
      "\u001b[1;31mPlease review the code in the cell(s) to identify a possible cause of the failure. \n",
      "\u001b[1;31mClick <a href='https://aka.ms/vscodeJupyterKernelCrash'>here</a> for more info. \n",
      "\u001b[1;31mView Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "root =\"csvs_for_ranking\"\n",
    "folders = os.listdir(root)\n",
    "\n",
    "import re\n",
    "\n",
    "def extract_seconds_from_folder(folder_name):\n",
    "    # Use regex to find the time pattern (hh:mm:ss)\n",
    "    match = re.search(r'(\\d+):(\\d+):(\\d+)', folder_name)\n",
    "    if match:\n",
    "        hours, minutes, seconds = map(int, match.groups())\n",
    "        # Convert to total seconds\n",
    "        return hours * 3600 + minutes * 60 + seconds\n",
    "    else:\n",
    "        # Return None if no time is found\n",
    "        return None\n",
    "\n",
    "\n",
    "\n",
    "for folder in folders:\n",
    "    csvs = os.listdir(root + \"/\"+folder)\n",
    "    for csv in csvs:\n",
    "        if (\"ground_truth\" in csv):\n",
    "            print(folder)\n",
    "\n",
    "\n",
    "            seconds = extract_seconds_from_folder(folder)\n",
    "\n",
    "            if (seconds > 2700 and \"England\" in csv):\n",
    "                myplayer = VideoPlayer(\"3-2024-2036178-Denmark_England.mp4\",8+971+seconds,0,[])\n",
    "            if (seconds < 2700 and \"England\" in csv):\n",
    "                myplayer = VideoPlayer(\"3-2024-2036178-Denmark_England.mp4\",8+seconds,0,[])\n",
    "            if (seconds < 2700 and \"Slovenia\" in csv):\n",
    "                myplayer = VideoPlayer(\"3-2024-2036165-slovenia-denmark.mp4\",8+954+seconds,0,[])\n",
    "            if (seconds < 2700 and \"Slovenia\" in csv):\n",
    "                myplayer = VideoPlayer(\"3-2024-2036165-slovenia-denmark.mp4\",8+seconds,0,[])\n",
    "            \n",
    "            \n",
    "            \n",
    "            df = pd.read_csv(root +\"/\"+folder+\"/\"+csv)\n",
    "            #Match_name, time, half\n",
    "            indices = df[[\"Time [s]\",\"half_team\",'Unnamed: 0', 'match_name']]\n",
    "            ratings = []\n",
    "            matches = df.match_name.unique()\n",
    "            for match_name in matches:\n",
    "                if \"England\" in match_name: \n",
    "                    myplayer = VideoPlayer(\"3-2024-2036178-Denmark_England.mp4\",8,8+971,indices[indices['match_name'] == match_name].to_numpy())\n",
    "                    [ratings.append(row) for row in myplayer.ratings]\n",
    "                if \"Slovenia\" in match_name:\n",
    "                    myplayer = VideoPlayer(\"3-2024-2036165-slovenia-denmark.mp4\",8,8+954,indices[indices['match_name'] == match_name].to_numpy())\n",
    "                    [ratings.append(row) for row in myplayer.ratings]\n",
    "            if (len(ratings) > 0):\n",
    "                ratings_df  = pd.DataFrame(ratings, columns=['Unnamed: 0',\"rating\"])\n",
    "                rated_situations = pd.merge(df, ratings_df, how =\"inner\", on=['Unnamed: 0'])\n",
    "                rated_situations =rated_situations.drop_duplicates('Unnamed: 0')\n",
    "                rated_situations.to_csv(root +\"/\"+folder+\"/\"+\"ranked_\"+csv)\n",
    "\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'ratings' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[11], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m ratings_df  \u001b[38;5;241m=\u001b[39m pd\u001b[38;5;241m.\u001b[39mDataFrame(\u001b[43mratings\u001b[49m, columns\u001b[38;5;241m=\u001b[39m[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mUnnamed: 0\u001b[39m\u001b[38;5;124m'\u001b[39m,\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mrating\u001b[39m\u001b[38;5;124m\"\u001b[39m])\n",
      "\u001b[0;31mNameError\u001b[0m: name 'ratings' is not defined"
     ]
    }
   ],
   "source": [
    "ratings_df  = pd.DataFrame(ratings, columns=['Unnamed: 0',\"rating\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "rated_situations = pd.merge(df, ratings_df, how =\"inner\", on=['Unnamed: 0'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "rated_situations =rated_situations.drop_duplicates('Unnamed: 0')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "    Unnamed: 0       match_name  Time [s] half_team        Time Min  rating\n",
      "0       179537  Denmark_England   1449.60        1H  0:24:09.600000       1\n",
      "1       174689  Denmark_England   1255.68        1H  0:20:55.680000       0\n",
      "3       199505  Denmark_England   2248.32        1H  0:37:28.320000       1\n",
      "5       149921  Denmark_England    264.96        1H  0:04:24.960000       1\n",
      "6       193697  Denmark_England   2016.00        1H         0:33:36       0\n",
      "7       208001  Denmark_England   2588.16        1H  0:43:08.160000       1\n",
      "8       238961  Denmark_England   3758.92        2H  1:02:38.920000       0\n",
      "9       253697  Denmark_England   4348.36        2H  1:12:28.360000       0\n",
      "10      176321  Denmark_England   1320.96        1H  0:22:00.960000       1\n",
      "11      185441  Denmark_England   1685.76        1H  0:28:05.760000       1\n"
     ]
    }
   ],
   "source": [
    "print(rated_situations)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "DBU",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
